### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by PawelKra** [geoxyIT/QMapa#2]
Zastąp to: Co się stało? Co chciałeś osiągnąć? 

## ŚRODOWISKO

Jakie środowisko było używane podczas napotkania problemu?

```ver
$ System operacyjny [Windows, macOS, Ubuntu...]
# MacOS

$ wersja QGIS
# 3.22

$ wersja wtyczki QMapa
#aktualna
```

## RAPORT Z BŁĘDEM
/python/plugins/QMapa/qmapa_dockwidget.py", line 117, in on_pbImport_clicked
              vev_lays_list = SimpleGmlImport().runImport(name, self.progressBar, self.cmbStylization.currentText())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/pawel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QMapa/src/simple_gml_import.py", line 251, in runImport
              ogr2ogr.main(["", "-f", "GPKG", gpkg_path, mod_gml_path])
              File "/home//.local/lib/python3.11/site-packages/osgeo_utils/samples/ogr2ogr.py", line 1113, in main
              or not TranslateLayer(
              ^^^^^^^^^^^^^^^
              File "/home//.local/lib/python3.11/site-packages/osgeo_utils/samples/ogr2ogr.py", line 1747, in TranslateLayer
              poFeature = poSrcLayer.GetNextFeature()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home//.local/lib/python3.11/site-packages/osgeo/ogr.py", line 1375, in GetNextFeature
              return _ogr.Layer_GetNextFeature(self, *args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             RuntimeError: Geometry of feature 592 PL.PZGiK.XXXX cannot be parsed: Curve: Got NULL geometry as Member instead of segments.. You may set the GML_SKIP_CORRUPTED_FEATURES configuration option to YES to skip to the next feature

## ODTWORZENIE BŁĘDU
Nie możecie, dane ewidencyjne w gml z konkretnym bledem trzeba mieć

## DODATKOWE UWAGI
sugestia jak naprawić w logu powyżej.

**Comment by Kamzarr** [comment]
Naprawione w wersji 2.1.0. Niedługo wersja zostanie opublikowana.
