### ISSUE TITLE
Błędne typy danych opisowych

### ISSUE THREAD

**Issue by jdusza1** [geoxyIT/QMapa#4]
Zastąp to: Co się stało? Co chciałeś osiągnąć? 

## ŚRODOWISKO

Jakie środowisko było używane podczas napotkania problemu?

```ver
$ System operacyjny [Windows, macOS, Ubuntu...]
# TODO: Windows

$ wersja QGIS
# TODO: 3.28.15

$ wersja wtyczki QMapa
# TODO: 2.2.0
```

## RAPORT Z BŁĘDEM
```raport
# TODO: Jeśli otrzymałeś raport z błędem wygenerowanym przez QGIS, wklej go tutaj
```

## ODTWORZENIE BŁĘDU
Błąd się objawia jedynie poprzez pozostawienie atrybutów warstwy działek: numer KW, OFU, OZU i OZK jako puste. Podczas dodania pliku GML bez wtyczki atrybuty są uzupełnione. Wtyczka rozpoznaje je jako typ JSON. Wczytywane pliki pobrano z powiatu łobeskiego oraz choszczeńskiego, ale dla powiatu choszczeńskiego numer KW importuje sie bez problemu. 

```opis
# TODO: nie dotyczy
```

## DODATKOWE UWAGI
typy danych po imporcie bez zastosowania wtyczki:
![bez wtyczki](https://github.com/geoxyIT/QMapa/assets/144669356/b3763bb2-b4ea-4cbd-9e0d-82881ff74109)
typy danych po imporcie za pomocą wtyczki:
![z wtyczką](https://github.com/geoxyIT/QMapa/assets/144669356/7614ee34-0af7-4afe-95f2-6bfb73e15967)

**Comment by Kamzarr** [comment]
Faktycznie, w najnowszej wersji wtyczki występuje problem dla atrybutów, które mogą wystąpić kilkukrotnie w jednym obiekcie (np. OFU, OZU i OZK mogą występować kilka razy w jednej działce ewidencyjnej). Wynika on z przejścia na VectorTranslate, zamiast ogr2ogr, które inaczej zapisuje takie powtórzone atrybuty. Są zapisywane do JSON, przez co nie są widoczne w tabeli atrybutów (można je jednak zobaczyć np. w kalkulatorze pól). Postaramy się to naprawić możliwie szybko w kolejnej aktualizacji.

**Comment by Kamzarr** [comment]
Naprawione w wersji 2.3.0. Niedługo zostanie opublikowana
